{{- if (empty .Values.configMapOverrideName) -}}
apiVersion: v1
kind: ConfigMap
metadata:
{{- with .Values.configMapAnnotations }}
  annotations:
    {{- toYaml .Values.configMapAnnotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "zelus-route-manager.labels" . | nindent 4 }}
    {{- with .Values.extraConfigmapLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: zelus-config
  namespace: {{ include "zelus-route-manager.namespace" . }}
data:
  zelus.yml: |
    protected_routes:
      {{- toYaml .Values.protectedRoutes | nindent 6 }}
{{- end -}}